language: php
php:
- 7.1
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
env:
  global:
  - secure: IlSrK2qQXO3UUTqdi83KlVr2dkdwQV/ROMle/PatHrw8e1vJX6upxeNpwCF39sYk7z1rXw7e6grT7fbf/PShecLciZuQRpizrHLilcRBCKOw6+EqaoGx2G8z7hCYaG9AChYEZeGm7WDoSFl8+W3zL+Aum3cAOzDU7hCYteS2cy41FGqnEsqAHNrpGx5sXu2FsOw9M0ra7LQu+9e6WYIeHlvjLqYqk9GBih9CNR9u2WCMhydszv7LecEzNvBCd9gyauk4K4SkeLBenjp3Ocyvbd/YXJP6DNSgWxVTysiU8HbLRErQZaNi2Hg1iIFfvsxD9zvGLr97FumnWpmX102enqhepB+dmrczIE9JSPnUju4kHo4kQD1+F4pNBSPb7HxKpqqi034xSYyc2vJsUZLpgep6/AF+sXHKgFgg7qnBk1YzIQVDbbJ3BOAawr+A19DHxNnPtGYOmxW137PUCrxZ6drlfBCsTrdRwDF0ut3yHDIZoARo0Eq4R8pwguclcPllttEyKdddt9jQQchHZDuagueIgUEKBkPK2G0tYNrcgWUFFduDxtfY3AKjf0Pu6+F62acSkYgNDDl9UXWotPYdfi48fN3iNtpCFf7I65RgmYzx6+7lGolvjiiOxol9m5OxnHoNTpOjTR0QjykZtTm0GmXFl3snpG8fzkE1YZ341LY=
  - secure: Xw7KiuLkTfgBm+Y7pxmdEAMPdZDQxFhF2GdP4yJx1W3b7b0fl6eMrSqhRGjURmJX9i3WFjeXt2ugXluKdonGZ0FL2+dgzTPZlB9GSQI0nDNUe1hmAtaCJKJjk6P28kxjBY3DApl9kITxpa0wBQ1DZ4uWs+ho4hPm6huPRwOyqKlzlHJCdUPBr8m3Ps6deoQ0u1st3RqPpe68iq8cjqr/jo9FLQ0pU6NrbXF1ElJKlbOMPVtTcH7MT4Awb4P2TmDZbRTn7IsVFJyaSPTaZ7OK/heiRT2T7SGBlIc1SuB+8Q1+BRA+RgjkxJG3j4uz7J9kmLkE8ynffbfdp1UjuTRzf6CVMA/p90FGWFMK46tHQCx/4A1K76BlVS2iJOFuRjBd+pfD/Un4TDKt8JefUXXYDakvz0zvTemBbHcghUVlEGL3ekJClS2ErzGXLpqVwySJ8x6ei9j8wj8fVsl2awN56XOPk4QelQK9b+LhInG3aV7MyFGN1ZzaIS6vab0L/E9bRgbZtTF4ID3PTAcYngckT6FKmEPAIsR/sWk+1wKTgsJOeVz2AUVKCU0f3CKwwJ/7ctg30/c9snRCOLvlCA/CmJV1VFwisK3nMXhZQwvbh21uXG1ssE28lft/h9zdmgPfBR7TFeVb7abApDF5vNSrTEEsxgqX8bvCbIosOFMPumo=
